apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: loc-products-components
  description: A collection of all products components
spec:
  targets:
    - ./component/component-service-products.yaml