apiVersion: backstage.io/v1alpha1
# https://backstage.io/docs/features/software-catalog/descriptor-format/#kind-api
kind: API
metadata:
  name: api-products
  description: This api exposes products functionality
spec:
  type: openapi
  lifecycle: production
  owner: tunas
  system: system-products
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: Products API
      license:
        name: MIT