name: Wilczura.Products - build, test and release all packages

on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  hello:
    runs-on: ubuntu-latest
    name: Hello
    steps:
      - name: Hello
        run: echo Hello
      
  application-tests:
    needs: hello
    uses: gwilczura/dotnet-common/.github/workflows/build-and-test.yml@main
    with:
      project-path: 'src/Wilczura.Products/Wilczura.Products.Application.Tests.Unit/Wilczura.Products.Application.Tests.Unit.csproj'
      unique-name: application-tests
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      
  architecture-tests:
    needs: application-tests
    uses: gwilczura/dotnet-common/.github/workflows/build-and-test.yml@main
    with:
      project-path: 'src/Wilczura.Products/Wilczura.Products.Tests.Architecture/Wilczura.Products.Tests.Architecture.csproj'
      unique-name: architecture-tests
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      
  integration-tests:
    needs: architecture-tests
    uses: gwilczura/dotnet-common/.github/workflows/build-and-test.yml@main
    with:
      project-path: 'src/Wilczura.Products/Wilczura.Products.Host.Tests.Integration/Wilczura.Products.Host.Tests.Integration.csproj'
      unique-name: integration-tests
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  contract-publish:
    needs: integration-tests
    uses: gwilczura/dotnet-common/.github/workflows/build-and-publish.yml@main
    with:
      project-path: 'src/Wilczura.Products/Wilczura.Products.Contract/Wilczura.Products.Contract.csproj'
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  client-publish:
    needs: integration-tests
    uses: gwilczura/dotnet-common/.github/workflows/build-and-publish.yml@main
    with:
      project-path: 'src/Wilczura.Products/Wilczura.Products.Client/Wilczura.Products.Client.csproj'
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
